---
name: eliud_pkg_follow
description: Eliud package for members following members
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_follow
version: 1.0.2+1
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  eliud_core: ^1.0.18+1
  eliud_pkg_etc: ^1.0.1+19
  eliud_pkg_notifications: ^1.0.1+19
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  transparent_image: ^2.0.0
  cloud_firestore: ^4.6.0
  http: ^0.13.5
  collection: ^1.17.0
  equatable: ^2.0.5
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  meta: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.7
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
